### ISSUE TITLE
Can't select project subdir / iTerm opens before directory selection

### ISSUE THREAD

**Issue by ptim** [afterdesign/MacTerminal#34]
Hi! tx for macterm.. love it daily!
This has worked for me until recently:

I expect: 

- trigger mac term while a project file is open,
- see a ST3 prompt offering a selection of directories within the project (including project root)
- select one
- iTerm should open to that directory

What happens now:

- trigger mac term while a project file is open,
- iTerm is focussed 
- the ST3 prompt offering a selection of directories is flashed briefly onscreen, no chance to make a selection
- iTerm opens cds to  the directory of the currently open file

please check the screencast: https://memelab.wistia.com/medias/ol1xd1x7wg#media

User settings:

```
{
    "terminal" : "iterm",
    "directory_mode" : "project",
    "debug": true
}
```

I've got debug switched on:

```
---MacTerminal DEBUG START---
{'cmd': '/usr/bin/osascript/Users/timosborn/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js/Users/timosborn/Documents/Clients/Common-Code/Meerqat/Source/meteor/client/views/_styleguide',
 'directory_mode': 'project',
 'err': b'',
 'out': b'\n',
 'terminal_name': 'iterm'}
---MacTerminal DEBUG END---
```

**Comment by ptim** [comment]
anyone else noticed this behaviour? I'm still seeing it on ST build 3083..

**Comment by afterdesign** [comment]
This should be fixed with version 4 that was just released.
