### ISSUE TITLE
iTerm doesn't change directory

### ISSUE THREAD

**Issue by ksnyde** [afterdesign/MacTerminal#36]
I have tried using both "terminal" and "iterm" and terminal works as expected but when I choose iterm (my primary terminal app) it opens a new tab but dumps me to the user's home directory. I do not have any configuration set other than the "terminal" setting.

**Comment by ksnyde** [comment]
I just noticed what is causing it problems. Here's a screenshot of an iTerm configuration I would typically use where (A) is an interactive window and (B) is a node watcher / build tool window. The problem is that these command were being inserted as text into the lower tab versus  the new tab that it created (and left in the default dir).

![2015-08-22_18-35-35_02](https://cloud.githubusercontent.com/assets/980757/9425138/00c4a374-48fd-11e5-8db0-044329d21e89.png)

**Comment by alancwoo** [comment]
Also having this problem and noticed it's doing the exact same thing, popping the command into the lower pane instead of the new tab. I tried playing around with the delays here and there thinking it was some kind of race condition but it still doesn't work. @afterdesign any ideas?

I'm using iTerm2 2.1.3, Sublime Build 3083, Mac 10.10.3 (zsh with zprezto/pure)

**Comment by afterdesign** [comment]
I have really no clue. I can't replicate this error. I'm creating new tab with cmd+shift+w and plugin is opening new main tab.

**Comment by alancwoo** [comment]
Just to be sure are you starting off with iterm having two horizontal split panes?

**Comment by afterdesign** [comment]
@alancwoo to be honest I have no idea how to start term with split panes. In arrangements settings ?

**Comment by afterdesign** [comment]
@alancwoo ok, I've finally figured out how to open split panes and I have no problems with opening new tab and going to correct directory.
