### ISSUE TITLE
Not changing directory with iTerm

### ISSUE THREAD

**Issue by akella** [afterdesign/MacTerminal#38]
Hi! Keep getting this error:
```
'---MacTerminal DEBUG START---'
{'cmd': '/usr/bin/osascript /Users/akella/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.scpt /Users/akella/Desktop/git',
 'directory_mode': 'project',
 'ext_language': 'scpt',
 'paths': ['/Users/akella/Desktop/git'],
 'process_err': b'/Users/akella/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.scpt:425:433: script error: Expected end of line but found identifier. (-2741)\n',
 'process_out': b''}
'---MacTerminal DEBUG END---'
```
But if i remove this part http://take.ms/oFA0J, works ok.
10.11 El Capitan, Sublime Text 3, Build 3083

**Comment by afterdesign** [comment]
@akella I've updated plugin to use JavaScript in El Capitan also.
But this error looks strange. Are you using iterm2 beta/nightly ? If so you have to set ```iterm-nightly``` in settings not ```iterm```.

**Comment by akella** [comment]
@afterdesign Ouch, you are right! I was using nightly, changed to iterm-nightly, works perfectly now! Sorry for even bothering you with such a minor issue.
