### ISSUE TITLE
Opens Iterm in home folder

### ISSUE THREAD

**Issue by billymedia** [afterdesign/MacTerminal#47]
Since upgrading to ST3, it keeps opening iTerm2 in my home folder. I have uninstalled / installed the package without luck. I have read all posts here and nothing seems to work. Your help would be appreciated as it worked like a charm before upgrading to ST3.

**Comment by eskirk** [comment]
Same here, definitely an issue with the most recent update to iterm because this feature stopped working right after I updated.

**Comment by afterdesign** [comment]
Ok. I'll try to find time tomorrow to check the issue.

**Comment by afterdesign** [comment]
I've tested newest build of ST3 and newest nightly build of iTerm2:
```
iTerm2 3.0.20160606-nightly is currently the newest version available.
```

I have no problems.
Remember that you need to set correct ```terminal```:
```
{
    "terminal"   :  "iterm-nightly"
}
```

**Comment by billymedia** [comment]
Iterm 2 - Build 3.0.20160606-nightly
Sublime Text 3 build is 3114.

This is my settings file:
`{
    "terminal" : "iterm-nightly",
    "osascript" : "/usr/bin/osascript",
    "debug" : false,
    "directory_mode" : "file"
}
`
![jun-06-2016 20-24-03](https://cloud.githubusercontent.com/assets/293540/15834731/cbea42ba-2c24-11e6-8815-306ff5eae971.gif)

**Comment by afterdesign** [comment]
@billymedia first turn on the debug mode and paste what it's showing in console.

**Comment by billymedia** [comment]
```
'---MacTerminal DEBUG START---'
{'cmd': '/usr/bin/osascript /Users/billypatel/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js /Users/billypatel/Sites/subism/swivel/build/src',
 'directory_mode': 'project',
 'ext_language': 'js',
 'paths': ['/Users/billypatel/Sites/subism/swivel/build/src'],
 'process_err': b'/Users/billypatel/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js:418:495: execution error: Error on line 23: Error: Message not understood. (-1708)\n',
 'process_out': b''}
'---MacTerminal DEBUG END---'
```

**Comment by afterdesign** [comment]
Ok, now we're getting somewhere. Still looks a bit strange.

First of all looks like the ```directory_mode``` is still ```project```. Please remove this completely from settings and restart sublime (sometimes it has some problems with updating configurations for plugins).
Second - check if the path ```/Users/billypatel/Sites/subism/swivel/build/src``` exists.
Third - what is your version of OS X ?

**Comment by billymedia** [comment]
1 - directory mode removed.
2 - Path exists, checked from the command line.
3 - Yosemite 10.10.5

**Comment by billymedia** [comment]
```
'---MacTerminal DEBUG START---'
{'cmd': '/usr/bin/osascript /Users/billypatel/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js /Users/billypatel/Sites/www/ssrpsys/expressionengine/templates/default_site/dashboard.group',
 'directory_mode': 'project',
 'ext_language': 'js',
 'paths': ['/Users/billypatel/Sites/www/ssrpsys/expressionengine/templates/default_site/dashboard.group'],
 'process_err': b'/Users/billypatel/Library/Application Support/Sublime Text 3/Packages/MacTerminal/macterminal_iterm.js:418:495: execution error: Error on line 23: Error: Message not understood. (-1708)\n',
 'process_out': b''}
'---MacTerminal DEBUG END---'
```

**Comment by billymedia** [comment]
Any update on this at all?

**Comment by afterdesign** [comment]
I'll try to debug this more. I was on vacation and didn't want to work ;)

**Comment by eheredia2511** [comment]
This seems to solve the problem.

Edit the file 
```
~/Library/Application Support/Sublime Text 3/Packages/MacTerminal\macterminal_iterm.js 
```
 and correct the line 23 to:

```
var currentTerminalSession = Terminal.currentWindow.currentSession;
```

**Comment by billymedia** [comment]
Nice one @eheredia2511 ! That worked.
